<?php

namespace Database\Seeders;

use App\Models\Ressource;
use App\Services\TruncateTableService;
use Illuminate\Database\Seeder;

class RessourceSeeder extends Seeder
{
    /**
     * The TruncateTableService instance.
     *
     * @var TruncateTableService
     */
    private $truncateTableService;

    /**
     * Constructor.
     *
     * @param TruncateTableService $truncateTableService
     */
    public function __construct(TruncateTableService $truncateTableService)
    {
        $this->truncateTableService = $truncateTableService;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->truncateTableService->truncateTable('ressource');
        $ressourceData = [
            ['id' => 1, 'titre_res' => 'Comment améliorer vos compétences en communication', 'contenu_res' => 'Découvrez des conseils pratiques pour améliorer votre communication interpersonnelle et professionnelle.', 'url_res' => 'https://random.imagecdn.app/500/500', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-02 14:25:25', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 2, 'titre_res' => 'Les grands classiques de la littérature mondiale', 'contenu_res' => 'Explorez les chefs-d\'œuvre de la littérature mondiale, de Shakespeare à Tolstoï.', 'url_res' => 'https://random.imagecdn.app/500/502', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-02 15:25:25', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 3, 'titre_res' => 'Entraînement intensif pour devenir un athlète', 'contenu_res' => 'Suivez un programme d\'entraînement intense pour améliorer votre condition physique et devenir un meilleur athlète.', 'url_res' => 'https://random.imagecdn.app/500/503', 'id_type_res' => 3, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-02 13:25:25', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 4, 'titre_res' => 'Comment gérer son budget et ses finances', 'contenu_res' => 'Apprenez à établir un budget, à économiser de l\'argent et à investir pour votre avenir financier.', 'url_res' => 'https://random.imagecdn.app/500/504', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-02 14:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 5, 'titre_res' => 'Les nouvelles technologies qui changeront le monde', 'contenu_res' => 'Découvrez les dernières innovations technologiques et comment elles pourraient façonner notre avenir.', 'url_res' => 'https://random.imagecdn.app/500/505', 'id_type_res' => 3, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-02 16:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 6, 'titre_res' => 'Guide pratique pour une alimentation saine', 'contenu_res' => 'Apprenez à manger sainement en suivant des conseils simples et des recettes nutritives.', 'url_res' => 'https://random.imagecdn.app/500/506', 'id_type_res' => 3, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-02 12:10:00', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 7, 'titre_res' => 'Les techniques de méditation pour le bien-être mental', 'contenu_res' => 'Explorez différentes techniques de méditation pour réduire le stress et améliorer votre bien-être mental.', 'url_res' => 'https://random.imagecdn.app/500/507', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-02 11:20:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 8, 'titre_res' => 'Conseils pour une vie plus écologique', 'contenu_res' => 'Découvrez des moyens simples de réduire votre empreinte écologique et de vivre de manière plus durable.', 'url_res' => 'https://random.imagecdn.app/500/508', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-02 10:05:00', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 9, 'titre_res' => 'Stratégies pour réussir vos études universitaires', 'contenu_res' => 'Apprenez des stratégies efficaces pour étudier, organiser votre temps et réussir vos examens à l\'université.', 'url_res' => 'https://random.imagecdn.app/500/509', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-02 09:15:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 10, 'titre_res' => 'Conseils pour une meilleure gestion du temps', 'contenu_res' => 'Découvrez des techniques pour gérer votre temps efficacement, prioriser vos tâches et atteindre vos objectifs.', 'url_res' => 'https://random.imagecdn.app/500/510', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-02 08:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 11, 'titre_res' => 'Les secrets d\'une communication efficace', 'contenu_res' => 'Découvrez les clés pour communiquer efficacement dans toutes les situations, que ce soit en public, en ligne ou en face à face.', 'url_res' => 'https://random.imagecdn.app/500/511', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-02 14:25:25', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 12, 'titre_res' => 'L\'art et la culture du monde entier', 'contenu_res' => 'Explorez la richesse de l\'art et de la culture à travers le monde, des grandes œuvres d\'art aux traditions culturelles uniques.', 'url_res' => 'https://random.imagecdn.app/500/512', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-02 15:25:25', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 13, 'titre_res' => 'Entraînement intensif pour devenir un athlète', 'contenu_res' => 'Suivez un programme d\'entraînement intense pour améliorer votre condition physique et devenir un meilleur athlète.', 'url_res' => 'https://random.imagecdn.app/500/153', 'id_type_res' => 3, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-02 13:25:25', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 14, 'titre_res' => 'Les dernières avancées technologiques', 'contenu_res' => 'Découvrez les toutes dernières avancées technologiques dans le domaine de la robotique, de l\'intelligence artificielle et bien plus encore.', 'url_res' => 'https://random.imagecdn.app/500/514', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-03 09:15:30', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 15, 'titre_res' => 'Comment gérer vos finances personnelles efficacement', 'contenu_res' => 'Apprenez des techniques et des stratégies pour gérer vos finances personnelles de manière responsable et efficace.', 'url_res' => 'https://random.imagecdn.app/5005/15', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-04 10:30:45', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 16, 'titre_res' => 'Guide pratique pour une éducation de qualité', 'contenu_res' => 'Découvrez des conseils pratiques pour améliorer la qualité de l\'éducation, que ce soit à l\'école, à la maison ou dans d\'autres environnements éducatifs.', 'url_res' => 'https://random.imagecdn.app/500/516', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-05 11:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 17, 'titre_res' => 'Les bienfaits d\'une vie saine', 'contenu_res' => 'Découvrez les nombreux avantages d\'un mode de vie sain, notamment sur la santé physique, mentale et émotionnelle.', 'url_res' => 'https://random.imagecdn.app/500/517', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-06 12:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 18, 'titre_res' => 'Les techniques de méditation pour la tranquillité d\'esprit', 'contenu_res' => 'Explorez différentes techniques de méditation pour réduire le stress, améliorer la concentration et trouver la tranquillité d\'esprit.', 'url_res' => 'https://random.imagecdn.app/500/518', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-07 14:20:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 19, 'titre_res' => 'Les bases de la nutrition pour une vie équilibrée', 'contenu_res' => 'Apprenez les principes fondamentaux de la nutrition pour une alimentation équilibrée et un mode de vie sain.', 'url_res' => 'https://random.imagecdn.app/500/519', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-08 16:30:00', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 20, 'titre_res' => 'Les nouvelles tendances dans le monde de l\'éducation', 'contenu_res' => 'Découvrez les nouvelles tendances et les innovations dans le domaine de l\'éducation, de l\'enseignement à distance à l\'apprentissage personnalisé.', 'url_res' => 'https://random.imagecdn.app/500/520', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-08 16:30:00', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 21, 'titre_res' => 'Les secrets d\'une communication efficace en ligne', 'contenu_res' => 'Découvrez comment communiquer efficacement en ligne, que ce soit par e-mail, sur les réseaux sociaux ou lors de réunions virtuelles.', 'url_res' => 'https://random.imagecdn.app/500/521', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-10 09:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 22, 'titre_res' => 'Exploration des arts du spectacle à travers les âges', 'contenu_res' => 'Découvrez l\'histoire et l\'évolution des arts du spectacle, y compris le théâtre, la danse, la musique et bien plus encore.', 'url_res' => 'https://random.imagecdn.app/500/522', 'id_type_res' => 2, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-02-11 10:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 23, 'titre_res' => 'Programme d\'entraînement pour devenir un marathonien', 'contenu_res' => 'Suivez un programme d\'entraînement complet pour vous préparer à courir un marathon, du renforcement musculaire à la nutrition.', 'url_res' => 'https://random.imagecdn.app/500/523', 'id_type_res' => 3, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-12 11:15:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 24, 'titre_res' => 'Les avancées révolutionnaires dans le domaine de la robotique', 'contenu_res' => 'Découvrez les dernières avancées dans le domaine de la robotique, de l\'intelligence artificielle et de la domotique, et leur impact sur notre vie quotidienne.', 'url_res' => 'https://random.imagecdn.app/500/524', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-13 12:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 25, 'titre_res' => 'Stratégies pour investir dans l\'immobilier', 'contenu_res' => 'Apprenez comment investir dans l\'immobilier de manière intelligente, en choisissant les bons biens et en maximisant vos rendements.', 'url_res' => 'https://random.imagecdn.app/500/525', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-14 14:30:00', 'is_archive' => 1, 'id_etat' => 2 ],
            ['id' => 26, 'titre_res' => 'Les nouvelles technologies éducatives à explorer', 'contenu_res' => 'Découvrez comment les nouvelles technologies, telles que l\'intelligence artificielle et la réalité virtuelle, transforment l\'apprentissage et l\'enseignement.', 'url_res' => 'https://random.imagecdn.app/500/526', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 1, 'date_creation' => '2022-02-15 15:20:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 27, 'titre_res' => 'Les bienfaits de l\'exercice physique pour la santé mentale', 'contenu_res' => 'Découvrez comment l\'exercice physique régulier peut aider à réduire le stress, l\'anxiété et la dépression, et à améliorer le bien-être mental.', 'url_res' => 'https://random.imagecdn.app/500/527', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-16 16:40:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 28, 'titre_res' => 'Les secrets d\'une alimentation équilibrée', 'contenu_res' => 'Apprenez comment équilibrer votre alimentation pour obtenir tous les nutriments essentiels dont votre corps a besoin pour rester en bonne santé.', 'url_res' => 'https://random.imagecdn.app/500/528', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-17 17:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 29, 'titre_res' => 'Les avantages du coaching en développement personnel', 'contenu_res' => 'Découvrez comment le coaching en développement personnel peut vous aider à atteindre vos objectifs, à améliorer vos compétences et à réaliser votre plein potentiel.', 'url_res' => 'https://random.imagecdn.app/500/529', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-02-18 09:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 30, 'titre_res' => 'Les grands artistes et mouvements artistiques du 20e siècle', 'contenu_res' => 'Explorez les œuvres et les mouvements artistiques qui ont marqué le 20e siècle, de l\'impressionnisme au surréalisme.', 'url_res' => 'https://random.imagecdn.app/500/530', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-19 10:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 31, 'titre_res' => 'Les meilleures techniques de relaxation pour réduire le stress', 'contenu_res' => 'Apprenez des techniques simples de relaxation, telles que la respiration profonde et la méditation, pour réduire le stress et améliorer votre bien-être.', 'url_res' => 'https://random.imagecdn.app/500/531', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-20 11:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 32, 'titre_res' => 'Les nouvelles technologies pour une mobilité durable', 'contenu_res' => 'Découvrez les dernières avancées technologiques dans le domaine de la mobilité durable, telles que les véhicules électriques et les transports en commun innovants.', 'url_res' => 'https://random.imagecdn.app/500/532', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-02-21 13:10:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 33, 'titre_res' => 'Comment épargner et investir pour sa retraite', 'contenu_res' => 'Apprenez comment épargner et investir intelligemment pour assurer une retraite confortable et sécurisée.', 'url_res' => 'https://random.imagecdn.app/500/533', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 2, 'date_creation' => '2022-02-22 14:25:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 34, 'titre_res' => 'Les tendances émergentes dans le domaine de l\'enseignement supérieur', 'contenu_res' => 'Découvrez les nouvelles tendances et les défis émergents dans le domaine de l\'enseignement supérieur, de l\'enseignement en ligne à l\'apprentissage expérientiel.', 'url_res' => 'https://random.imagecdn.app/500/534', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-23 15:40:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 35, 'titre_res' => 'Les bases de la médecine préventive', 'contenu_res' => 'Apprenez les principes fondamentaux de la médecine préventive pour maintenir une bonne santé tout au long de votre vie.', 'url_res' => 'https://random.imagecdn.app/500/535', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-02-24 16:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 36, 'titre_res' => 'Les bienfaits du yoga pour le corps et l\'esprit', 'contenu_res' => 'Découvrez comment le yoga peut aider à renforcer le corps, à calmer l\'esprit et à améliorer votre bien-être général.', 'url_res' => 'https://random.imagecdn.app/500/36', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-02-25 17:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 37, 'titre_res' => 'Les technologies émergentes dans le domaine de la santé', 'contenu_res' => 'Découvrez les dernières technologies émergentes qui révolutionnent le domaine de la santé, de la télémédecine aux dispositifs médicaux intelligents.', 'url_res' => 'https://random.imagecdn.app/500/537', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-26 09:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 38, 'titre_res' => 'Les meilleures pratiques pour la gestion du stress au travail', 'contenu_res' => 'Apprenez des stratégies efficaces pour gérer le stress au travail, rester calme sous pression et maintenir un équilibre entre vie professionnelle et vie personnelle.', 'url_res' => 'https://random.imagecdn.app/500/538', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 2, 'date_creation' => '2022-02-27 10:15:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 39, 'titre_res' => 'Les secrets de la créativité artistique', 'contenu_res' => 'Découvrez des techniques pour stimuler votre créativité artistique et exprimer votre vision unique à travers l\'art.', 'url_res' => 'https://random.imagecdn.app/500/539', 'id_type_res' => 2, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-02-28 11:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 40, 'titre_res' => 'Guide pratique pour la planification financière', 'contenu_res' => 'Apprenez à élaborer un plan financier solide pour atteindre vos objectifs à long terme, que ce soit pour l\'épargne, l\'investissement ou la retraite.', 'url_res' => 'https://random.imagecdn.app/500/540', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 3, 'date_creation' => '2022-03-01 12:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 41, 'titre_res' => 'Les tendances émergentes dans le secteur de la technologie financière', 'contenu_res' => 'Découvrez les dernières tendances dans le secteur de la technologie financière, telles que les paiements sans contact, la blockchain et les robo-conseillers.', 'url_res' => 'https://random.imagecdn.app/500/541', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 2, 'date_creation' => '2022-03-02 13:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 42, 'titre_res' => 'Les nouvelles approches de l\'enseignement des sciences', 'contenu_res' => 'Explorez de nouvelles méthodes d\'enseignement des sciences pour engager les élèves et encourager la curiosité scientifique.', 'url_res' => 'https://random.imagecdn.app/500/542', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-03-03 14:20:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 43, 'titre_res' => 'Les meilleures applications mobiles pour la santé et le bien-être', 'contenu_res' => 'Découvrez des applications mobiles innovantes pour vous aider à suivre votre santé, à gérer votre stress et à améliorer votre bien-être général.', 'url_res' => 'https://random.imagecdn.app/500/543', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-03-04 15:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 44, 'titre_res' => 'Les principes de base de la méditation pour les débutants', 'contenu_res' => 'Apprenez les principes fondamentaux de la méditation pour débutants, y compris la posture, la respiration et la concentration.', 'url_res' => 'https://random.imagecdn.app/500/544', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-03-05 16:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 45, 'titre_res' => 'Les meilleures pratiques pour une alimentation saine et équilibrée', 'contenu_res' => 'Découvrez des conseils et des astuces pour adopter une alimentation saine et équilibrée, en incluant une variété de fruits, de légumes, de protéines et de grains entiers dans votre régime alimentaire.', 'url_res' => 'https://random.imagecdn.app/500/545', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-03-06 17:55:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 46, 'titre_res' => 'Les dernières tendances en matière de fitness et d\'entraînement', 'contenu_res' => 'Découvrez les dernières tendances en matière de fitness et d\'entraînement, des entraînements haute intensité à la musculation fonctionnelle.', 'url_res' => 'https://random.imagecdn.app/500/546', 'id_type_res' => 3, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-03-07 09:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 47, 'titre_res' => 'Les nouveaux développements dans le domaine de la biotechnologie', 'contenu_res' => 'Découvrez les derniers développements dans le domaine de la biotechnologie, de la médecine régénérative aux organismes génétiquement modifiés.', 'url_res' => 'https://random.imagecdn.app/500/547', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-03-08 10:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 48, 'titre_res' => 'Les secrets d\'une gestion efficace du temps', 'contenu_res' => 'Apprenez des stratégies pour gérer votre temps de manière efficace, prioriser les tâches et éviter la procrastination.', 'url_res' => 'https://random.imagecdn.app/500/548', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 1, 'date_creation' => '2022-03-09 11:30:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 49, 'titre_res' => 'Les dernières tendances en matière de design web', 'contenu_res' => 'Découvrez les dernières tendances en matière de design web, des mises en page créatives aux animations interactives.', 'url_res' => 'https://random.imagecdn.app/500/549', 'id_type_res' => 1, 'id_vis' => 2, 'id_createur' => 3, 'date_creation' => '2022-03-10 12:45:00', 'is_archive' => 0, 'id_etat' => 2 ],
            ['id' => 50, 'titre_res' => 'Les bases de la programmation informatique', 'contenu_res' => 'Apprenez les concepts fondamentaux de la programmation informatique, y compris les variables, les boucles et les fonctions.', 'url_res' => 'https://random.imagecdn.app/500/550', 'id_type_res' => 1, 'id_vis' => 1, 'id_createur' => 2, 'date_creation' => '2022-03-11 13:50:00', 'is_archive' => 0, 'id_etat' => 2 ],
        ];

        foreach ($ressourceData as $ressource) {
            Ressource::create([
                'id' => $ressource['id'],
                'titre_res' => $ressource['titre_res'],
                'contenu_res' => $ressource['contenu_res'],
                'url_res' => $ressource['url_res'],
                'id_type_res' => $ressource['id_type_res'],
                'id_vis' => $ressource['id_vis'],
                'id_createur' => $ressource['id_createur'],
                'date_creation' => $ressource['date_creation'],
                'is_archive' => $ressource['is_archive'],
                'id_etat' => $ressource['id_etat']
            ]);
        }
    }
}


