name: Laravel API CI

on:
  push:
    branches:
      - TestAndProtectedRoutes

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Display initial .env content
        run: cat .env || echo ".env file does not exist yet"

      - name: Setup environment variables
        run: |
          echo "APP_NAME=${{ vars.APP_NAME }}" >> .env
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=${{ vars.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ vars.APP_URL }}" >> .env
          echo "DB_CONNECTION=${{ vars.DB_CONNECTION }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_FOREIGN_KEYS=${{ vars.DB_FOREIGN_KEYS }}" >> .env
          echo "CACHE_DRIVER=${{ vars.CACHE_DRIVER }}" >> .env
          echo "SESSION_DRIVER=${{ vars.SESSION_DRIVER }}" >> .env
          echo "QUEUE_CONNECTION=${{ vars.QUEUE_CONNECTION }}" >> .env
          echo "MAIL_MAILER=${{ vars.MAIL_MAILER }}" >> .env
          echo "BROADCAST_DRIVER=${{ vars.BROADCAST_DRIVER }}" >> .env
          echo "FILESYSTEM_DRIVER=${{ vars.FILESYSTEM_DRIVER }}" >> .env

      - name: Display final .env content
        run: cat .env

      - name: Create SQLite database file
        run: touch /tmp/database.sqlite

      - name: Run migrations before tests
        run: |
          php artisan migrate
          php artisan migrate:status

      - name: List SQLite tables
        run: |
          sqlite3 /tmp/database.sqlite ".tables"

      - name: Seed the database
        run: php artisan db:seed

      - name: Run PHPUnit tests
        run: php artisan test
