name: Laravel API CI

on:
  push:
    branches:
      - TestAndProtectedRoutes

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    environment: Test back-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup environment variables
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_FOREIGN_KEYS=${{ secrets.DB_FOREIGN_KEYS }}" >> .env
          echo "CACHE_DRIVER=${{ secrets.CACHE_DRIVER }}" >> .env
          echo "SESSION_DRIVER=${{ secrets.SESSION_DRIVER }}" >> .env
          echo "QUEUE_CONNECTION=${{ secrets.QUEUE_CONNECTION }}" >> .env
          echo "MAIL_MAILER=${{ secrets.MAIL_MAILER }}" >> .env
          echo "BROADCAST_DRIVER=${{ secrets.BROADCAST_DRIVER }}" >> .env
          echo "FILESYSTEM_DRIVER=${{ secrets.FILESYSTEM_DRIVER }}" >> .env

      - name: Create SQLite database file
        run: touch /tmp/database.sqlite

      - name: Run migrations before tests
        run: php artisan migrate

      - name: Seed the database
        run: php artisan db:seed

      - name: Run PHPUnit tests
        run: php artisan test

  run-sonar:
    runs-on: ubuntu-latest
    environment: Raspberry
    needs: laravel-tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # merge-develop-main:
  #   runs-on: ubuntu-latest
  #   environment: Raspberry
  #   needs: laravel-tests
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     # Étape 1 : Transférer les fichiers vers le serveur via SSH (si nécessaire)
  #     - name: Copy repository to server
  #       uses: appleboy/scp-action@v0.1.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         source: "." # Transférer tous les fichiers ou un sous-ensemble
  #         target: "/var/www/html/Cube-Back" # Remplace par le chemin cible sur ton serveur

  #     # Étape 2 : Fusionner la branche develop sur main via SSH
  #     - name: Merge Develop into Main on Remote Server
  #       uses: appleboy/ssh-action@v0.1.5
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         script: |
  #           cd /var/www/html/Cube-Back
  #           git checkout main
  #           git pull origin main
  #           git merge develop
  #           git push origin main

  #     # Étape 3 : Redémarrer le serveur Apache (si nécessaire)
  #     - name: Restart Apache server
  #       uses: appleboy/ssh-action@v0.1.5
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         script: sudo systemctl restart apache2
