name: Laravel API CI

on:
  push:
    branches:
      - TestAndProtectedRoutes

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Installation de PHP et des dépendances
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Étape 3 : Générer le fichier .env pour les tests
      - name: Setup environment file
        run: cp .env.example .env

      # Étape 4 : Générer la clé d'application
      # - name: Generate Laravel application key
      #   run: php artisan key:generate

      # Étape 5 : Lancer les migrations pour préparer la base de données SQLite
      - name: Run migrations
        run: php artisan migrate --env=testing --no-interaction -vvv

      # Étape 6 : Lancer les tests PHPUnit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
