name: Laravel API CI
# Changement
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # laravel-tests:
  #   runs-on: ubuntu-latest
  #   environment: Test back-end
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Setup PHP
  #       uses: shivammathur/setup-php@v2
  #       with:
  #         php-version: "8.2"

  #     - name: Install Composer dependencies
  #       run: composer install --prefer-dist --no-progress --no-suggest

  #     - name: Setup environment variables
  #       run: |
  #         echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
  #         echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
  #         echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
  #         # Ajoute les autres variables ici

  #     - name: Create SQLite database file
  #       run: touch /tmp/database.sqlite

  #     - name: Run migrations before tests
  #       run: php artisan migrate

  #     - name: Seed the database
  #       run: php artisan db:seed

  #     - name: Run PHPUnit tests
  #       run: php artisan test

  run-sonar:
    runs-on: ubuntu-latest
    needs: laravel-tests
    environment: Raspberry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pull-on-server:
    runs-on: ubuntu-latest
    environment: Raspberry
    needs: [run-sonar]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH for connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Git pull on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/Cube-Back
            git pull origin main

      - name: Restart Apache server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo systemctl restart apache2
