name: Laravel API CI

on:
  push:
    branches:
      - develop

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Installation de PHP et des dépendances
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Étape 6 : Lancer les tests PHPUnit
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit

        
    # # Étape 5 : Transférer les fichiers vers le serveur via SSH (avec mot de passe)
    # - name: Copy files via SSH
    #   uses: appleboy/scp-action@v0.1.3
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     source: 'dist/*'
    #     target: '/var/www/html/Cube-Front'

    # # Étape 6 : Redémarrer le serveur Apache (si nécessaire)
    # - name: Restart Apache server
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USER }}
    #     password: ${{ secrets.SSH_PASSWORD }}
    #     script: sudo systemctl restart apache2
