name: Laravel API CI

on:
  push:
    branches:
      - TestAndProtectedRoutes

jobs:
  # Job 1: Setup repository and install dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup environment variables
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_FOREIGN_KEYS=${{ secrets.DB_FOREIGN_KEYS }}" >> .env
          echo "CACHE_DRIVER=${{ secrets.CACHE_DRIVER }}" >> .env
          echo "SESSION_DRIVER=${{ secrets.SESSION_DRIVER }}" >> .env
          echo "QUEUE_CONNECTION=${{ secrets.QUEUE_CONNECTION }}" >> .env
          echo "MAIL_MAILER=${{ secrets.MAIL_MAILER }}" >> .env
          echo "BROADCAST_DRIVER=${{ secrets.BROADCAST_DRIVER }}" >> .env
          echo "FILESYSTEM_DRIVER=${{ secrets.FILESYSTEM_DRIVER }}" >> .env

      - name: Create SQLite database file
        run: touch /tmp/database.sqlite

      - name: Save dependencies and environment file
        uses: actions/upload-artifact@v2
        with:
          name: app-data
          path: |
            vendor/
            .env
            /tmp/database.sqlite

  # Job 2: Setup environment and database (download artifacts)
  setup-environment:
    runs-on: ubuntu-latest
    needs: setup  # Ce job dépend du job précédent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download environment and dependencies
        uses: actions/download-artifact@v2
        with:
          name: app-data

      - name: Run migrations before tests
        run: php artisan migrate
        working-directory: ./ # Assure-toi d'être dans le bon répertoire

      - name: Seed the database
        run: php artisan db:seed
        working-directory: ./ # Ajoute le répertoire du projet Laravel

  # Job 3: Run PHPUnit tests (download artifacts)
  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment  # Ce job dépend du job précédent
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download environment and dependencies
        uses: actions/download-artifact@v2
        with:
          name: app-data

      - name: Run PHPUnit tests
        run: php artisan test
        working-directory: ./ # Ajoute le répertoire du projet Laravel
