name: Laravel API CI

on:
  push:
    branches:
      - TestAndProtectedRoutes

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: Test back-end

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup environment variables
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/tmp/database.sqlite" >> .env
          echo "CACHE_DRIVER=file" >> .env
          echo "SESSION_DRIVER=file" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env

      - name: Create SQLite database file
        run: touch /tmp/database.sqlite

      - name: Run migrations
        run: php artisan migrate --no-interaction --force

      - name: Seed the database
        run: php artisan db:seed --no-interaction --force

      - name: Upload SQLite database as artifact
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: /tmp/database.sqlite

  tests:
    runs-on: ubuntu-latest
    environment: Test back-end
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Download database artifact
        uses: actions/download-artifact@v4
        with:
          name: database
          path: /tmp

      - name: Run PHPUnit tests
        run: php artisan test
